### ISSUE TITLE
Rigol MSO5074 crashes when we try to do stuff with glscopeclient

### ISSUE THREAD

**Issue by kench** [azonenberg/scopehal-apps#249] opened 2020-10-24 02:21 UTC
I need to include packet captures, but both the scope and glscopehal become unresponsive.

**Comment by azonenberg** [comment] 2020-10-24 05:08
Possibly related to #146.

To avoid overlap, this ticket specifically for the *scope firmware* hanging, not glscopeclient.

**Comment by electroniceel** [comment] 2020-10-24 08:20
Degi was able to reproduce the crash with this short code snippet: http://paste.debian.net/1165913/

(Posted on IRC here: https://freenode.irclog.whitequark.org/scopehal/2020-10-04#28061962 )

**Comment by bvernoux** [comment] 2020-10-25 08:42
I cannot reproduce that issue with my Rigol MSO5000 (HW 01.01.00) and latest firmware 01.03.00.01 
Anyway so far on windows glscopeclient is unusable with something less than 1 frame per second...

**Comment by azonenberg** [comment] 2020-11-05 02:14
Believed fixed with latest Rigol firmware.

**Closed by azonenberg** 2020-11-05 02:14 UTC
