### ISSUE TITLE
Error when launching glscopeclient on XUbuntu 18.04 LTS missing styles dir and glscopeclient.css file

### ISSUE THREAD

**Issue by bvernoux** [azonenberg/scopehal-apps#40] opened 2019-04-27 07:13 UTC
I have finally built with success glscope using scopehal-cmake on VirtualBox XUbuntu 18.04.02 LTS but I have an error when I launch the glscopeclient it seems there is a missing css file see error below:

```
hydra@hydra-VirtualBox:~/scopehal-cmake/build/src/glscopeclient$ ./glscopeclient 

(glscopeclient:18901): glibmm-CRITICAL **: 09:03:59.931: 
unhandled exception (type Glib::Error) in signal handler:
domain: gtk-css-provider-error-quark
code  : 2
what  : <broken file>:1:0Failed to import: Error opening file /home/hydra/scopehal-cmake/build/src/glscopeclient/styles/glscopeclient.css: No such file or directory
```

I confirm **styles** directory does not exist after build so **styles/glscopeclient.css** is not found
```
hydra@hydra-VirtualBox:~/scopehal-cmake/build/src/glscopeclient$ ls -l
total 4880
drwxrwxr-x 3 hydra hydra    4096 Apr 27 09:02 CMakeFiles
-rw-rw-r-- 1 hydra hydra    1141 Apr 26 20:02 cmake_install.cmake
-rwxrwxr-x 1 hydra hydra 4964224 Apr 26 20:08 glscopeclient
-rw-rw-r-- 1 hydra hydra   23850 Apr 26 20:02 Makefile
```

**Comment by azonenberg** [comment] 2019-04-27 08:34
glscopeclient expects to be run from the source directory. There's a hard coded chdir() that's probably failing on your system because it uses an absolute path on my workstation.

Closing this as it's effectively a duplicate of #15.

**Closed by azonenberg** 2019-04-27 08:34 UTC
